// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace practicaExamen.Entities
{
    [DbContext(typeof(practicaExamenContext))]
    partial class practicaExamenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("practicaExamen.Models.Carro", b =>
                {
                    b.Property<string>("placa")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<double>("cilindraje")
                        .HasColumnType("float");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("propietarioIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("placa");

                    b.HasIndex("propietarioIdentificacion");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("practicaExamen.Models.Propietario", b =>
                {
                    b.Property<string>("identificaion")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("identificaion");

                    b.ToTable("Propietario");
                });

            modelBuilder.Entity("practicaExamen.Models.Carro", b =>
                {
                    b.HasOne("practicaExamen.Models.Propietario", "propietario")
                        .WithMany()
                        .HasForeignKey("propietarioIdentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("propietario");
                });
#pragma warning restore 612, 618
        }
    }
}
